apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: tekton-steps
spec:
  steps:
    - name: step1
      image: ubuntu  # contains bash
      script: |
        #!/usr/bin/env bash
        echo "Hello from Bash!"
    - name: step2
      image: python  # contains python
      script: |
        #!/usr/bin/env python
        print("Hello from python")
    - name: step3
      image: node  # contains node
      script: |
        #!/usr/bin/env node
        console.log("Hello from Node!")
